"""
This file contains constants used throughout the codebase.
"""
SHORT_STR_LEN = 100
LONG_STR_LEN = 10000
TINY_STR_LEN = 15
LANG_CODE_STR_LEN = 5


HEADING = 'HEADING'
PARAGRAPH = 'PARAGRAPH'
IMAGE = 'IMAGE'
VIDEO = 'VIDEO'
BUTTON = 'BUTTON'
LIST = 'LIST'
FORM = 'FORM'
RICH_TEXT = 'RICH_TEXT'
ACCORDION = 'ACCORDION'
DIVIDER = 'DIVIDER'
