# Generated by Django 2.2.2 on 2019-07-02 14:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='properties',
            field=models.ManyToManyField(blank=True, to='database.ActionProperty'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='action_tags', to='database.Tag'),
        ),
        migrations.AlterField(
            model_name='action',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='database.Vendor'),
        ),
        migrations.AlterField(
            model_name='actionproperty',
            name='community',
            field=models.ManyToManyField(blank=True, to='database.Community'),
        ),
        migrations.AlterField(
            model_name='billingstatement',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='policies',
            field=models.ManyToManyField(blank=True, to='database.Policy'),
        ),
        migrations.AlterField(
            model_name='communityadmingroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='database.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='database.Tag'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(blank=True, to='database.PageSection'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slides',
            field=models.ManyToManyField(blank=True, to='database.SliderImage'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='buttons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tagcollection',
            name='tags',
            field=models.ManyToManyField(blank=True, to='database.Tag'),
        ),
        migrations.AlterField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='team_admins', to='database.UserProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals',
            field=models.ManyToManyField(blank=True, to='database.Goal'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='database.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='database.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='database.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, to='database.Community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, to='database.Goal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_estate_units',
            field=models.ManyToManyField(blank=True, related_name='user_real_estate_units', to='database.RealEstateUnit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='database.Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='services',
            field=models.ManyToManyField(blank=True, to='database.Service'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='verification_checklist',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
