# Generated by Django 2.2.3 on 2019-07-18 16:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='graph',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='denominator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Tag'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Graph'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Media')),
            ],
        ),
        migrations.AddField(
            model_name='pagesection',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='database.Button'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='cards',
            field=models.ManyToManyField(blank=True, to='database.Card'),
        ),
    ]
