# Generated by Django 2.2.3 on 2019-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190718_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='data',
            field=models.ManyToManyField(blank=True, to='database.Data'),
        ),
    ]
