# Generated by Django 2.2.2 on 2019-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190702_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
