# Generated by Django 2.2.2 on 2019-07-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190702_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.TagCollection'),
        ),
    ]
