# Generated by Django 2.2.3 on 2019-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190718_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_community_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
