# Generated by Django 2.2.2 on 2019-07-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_tag_tag_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Community'),
        ),
    ]
