# Generated by Django 2.2.3 on 2019-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190718_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='owner',
        ),
        migrations.AddField(
            model_name='community',
            name='owner_email',
            field=models.EmailField(default='etohn@massenergize.org', max_length=100),
        ),
        migrations.AddField(
            model_name='community',
            name='owner_name',
            field=models.EmailField(default='Ellen', max_length=100),
        ),
    ]
