# Generated by Django 2.2.2 on 2019-07-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190705_0117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
