# Generated by Django 2.2.3 on 2019-07-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190719_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
    ]
