# Generated by Django 2.2.3 on 2019-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190706_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='is_external_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractionrel',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE'), ('SAVE FOR LATER', 'SAVE_FOR_LATER')], db_index=True, default='TODO', max_length=100),
        ),
    ]
