# Generated by Django 2.2.3 on 2019-07-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_community_accepted_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner_name',
            field=models.CharField(default='Ellen', max_length=100),
        ),
    ]
