# Generated by Django 2.2.3 on 2019-07-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190719_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_geographically_focused',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailcategory',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_external_event',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tagcollection',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
