# Generated by Django 2.2.3 on 2019-07-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190712_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Community'),
        ),
    ]
