# Generated by Django 2.2.3 on 2019-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190719_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='graphs',
            field=models.ManyToManyField(blank=True, related_name='graphs', to='database.Graph'),
        ),
    ]
