# Generated by Django 2.2.3 on 2019-07-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_graph_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('name',), 'verbose_name_plural': 'Data'},
        ),
        migrations.RemoveField(
            model_name='billingstatement',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='value',
        ),
    ]
