# Generated by Django 2.2.3 on 2019-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190712_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('name', 'value'), 'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='billingstatement',
            name='amount',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='statistic',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
