# Generated by Django 2.2.3 on 2019-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190712_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractionrel',
            options={'ordering': ('status', 'user', 'action')},
        ),
        migrations.AddField(
            model_name='realestateunit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
