# Generated by Django 2.2.3 on 2019-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_pagesection_graph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionproperty',
            options={'ordering': ('id',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ('text',)},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='actionproperty',
            name='community',
        ),
        migrations.RemoveField(
            model_name='actionproperty',
            name='order_position',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='buttons',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='database.Button'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='onboarding_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
