# Generated by Django 2.2.3 on 2019-07-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_event_more_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractionrel',
            unique_together={('user', 'action')},
        ),
    ]
