# Generated by Django 2.2.3 on 2019-07-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20190722_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestimonialsRel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Action')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Testimonial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Vendor')),
            ],
            options={
                'ordering': ('user', 'testimonial', 'action'),
                'unique_together': {('user', 'testimonial', 'action', 'vendor')},
            },
        ),
    ]
