# Generated by Django 2.2.3 on 2019-07-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_usertestimonialsrel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTestimonialsRel',
            new_name='UserTestimonialRel',
        ),
    ]
