# Generated by Django 2.2.3 on 2019-07-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190723_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionrel',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Media'),
        ),
    ]
