# Generated by Django 2.2.3 on 2019-07-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20190723_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestimonialrel',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community'),
        ),
    ]
