# Generated by Django 2.2.3 on 2019-07-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_usertestimonialrel_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='communities',
            field=models.ManyToManyField(blank=True, to='database.Community'),
        ),
        migrations.AlterField(
            model_name='usertestimonialrel',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Action'),
        ),
        migrations.AlterField(
            model_name='usertestimonialrel',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Testimonial'),
        ),
    ]
