# Generated by Django 2.2.3 on 2019-07-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20190724_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='file',
            new_name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Action'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together={('user', 'action')},
        ),
        migrations.DeleteModel(
            name='UserTestimonialRel',
        ),
    ]
