# Generated by Django 2.2.3 on 2019-07-25 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20190725_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
