# Generated by Django 2.2.3 on 2019-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20190725_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepts_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
