# Generated by Django 2.2.3 on 2019-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_userprofile_accepts_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited_communities',
            field=models.ManyToManyField(blank=True, related_name='invited_communites', to='database.Community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepts_terms_and_conditions',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
