# Generated by Django 2.2.3 on 2019-08-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20190807_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('attendee', 'event')},
        ),
    ]
