# Generated by Django 2.2.3 on 2019-08-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20190816_0041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractionrel',
            unique_together={('user', 'action', 'real_estate_unit')},
        ),
    ]
