# Generated by Django 2.2.3 on 2019-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20190816_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('order', 'name', 'tag_collection')},
        ),
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together=set(),
        ),
    ]
