# Generated by Django 2.2.3 on 2019-09-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20190829_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('IMG', 'Image'), ('VIDEO', 'Video'), ('UNKNOWN', 'Other')], default='Other', max_length=100),
        ),
    ]
