# Generated by Django 2.2.5 on 2019-09-27 16:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20190920_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_phone', models.CharField(blank=True, max_length=100)),
                ('primary_email', models.CharField(blank=True, max_length=100)),
                ('secondary_phone', models.CharField(blank=True, max_length=100)),
                ('secondary_email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('buttons', models.ManyToManyField(blank=True, to='database.Button')),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('events', models.ManyToManyField(blank=True, to='database.Event')),
                ('graphs', models.ManyToManyField(to='database.Graph')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
        ),
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('buttons', models.ManyToManyField(blank=True, to='database.Button')),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('graphs', models.ManyToManyField(to='database.Graph')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
        ),
        migrations.CreateModel(
            name='ActionsPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('buttons', models.ManyToManyField(blank=True, to='database.Button')),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('events', models.ManyToManyField(blank=True, to='database.Event')),
                ('graphs', models.ManyToManyField(to='database.Graph')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('buttons', models.ManyToManyField(blank=True, to='database.Button')),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
        ),
    ]
