# Generated by Django 2.2.5 on 2019-10-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20190920_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='goal',
            name='attained_carbon_footprint_reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='attained_number_of_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='attained_number_of_households',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_carbon_footprint_reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_number_of_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_number_of_households',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
