# Generated by Django 2.2.5 on 2019-10-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_aboutuspage_actionspage_contact_contactuspage_donatepage_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='actionspage',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='actionspage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='actionspage',
            name='events',
        ),
        migrations.RemoveField(
            model_name='actionspage',
            name='graphs',
        ),
        migrations.RemoveField(
            model_name='actionspage',
            name='images',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='graphs',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='community',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='events',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='graphs',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='images',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('order',)},
        ),
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
        migrations.DeleteModel(
            name='ActionsPage',
        ),
        migrations.DeleteModel(
            name='ContactUsPage',
        ),
        migrations.DeleteModel(
            name='DonatePage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
