# Generated by Django 2.2.5 on 2019-10-09 13:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20191004_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.AddField(
            model_name='goal',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('community', 'name')},
        ),
        migrations.CreateModel(
            name='ImpactPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'ImpactPageSettings',
                'db_table': 'impact_page_settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('featured_links', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('featured_events', models.ManyToManyField(blank=True, to='database.Event')),
                ('featured_stats', models.ManyToManyField(blank=True, to='database.Data')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'HomePageSettings',
                'db_table': 'home_page_settings',
            },
        ),
        migrations.CreateModel(
            name='DonatePageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'DonatePageSettings',
                'db_table': 'donate_page_settings',
            },
        ),
        migrations.CreateModel(
            name='ContactUsPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'ContactUsPageSettings',
                'db_table': 'contact_us_page_settings',
            },
        ),
        migrations.CreateModel(
            name='ActionsPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'ActionsPageSettings',
                'db_table': 'actions_page_settings',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.TextField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'AboutUsPageSettings',
                'db_table': 'about_us_page_settings',
            },
        ),
    ]
