# Generated by Django 2.2.5 on 2019-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20191009_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='attained_carbon_footprint_reduction',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='attained_number_of_actions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='attained_number_of_households',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_carbon_footprint_reduction',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_number_of_actions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_number_of_households',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
