# Generated by Django 2.2.5 on 2019-10-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20191009_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
        migrations.AddField(
            model_name='community',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Goal'),
        ),
        migrations.AddField(
            model_name='team',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Goal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Goal'),
        ),
    ]
