# Generated by Django 2.2.5 on 2019-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20191010_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_events',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_links',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_stats',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_video',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
