# Generated by Django 2.2.5 on 2019-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20191015_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='database.Tag'),
        ),
    ]
