# Generated by Django 2.2.5 on 2019-10-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_testimonial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='actionspagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contactuspagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donatepagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='impactpagesettings',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
