# Generated by Django 2.2.5 on 2019-10-20 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20191020_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='key_contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
