# Generated by Django 2.2.5 on 2019-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20191023_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='action',
            name='featured_summary',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actionspagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactuspagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donatepagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
