# Generated by Django 2.2.5 on 2019-10-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20191023_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('order', 'name')},
        ),
    ]
