# Generated by Django 2.2.5 on 2019-10-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_auto_20191024_0025'),
        ('database', '0047_auto_20191028_0215'),
    ]

    operations = [
    ]
