# Generated by Django 2.2.5 on 2019-11-01 01:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_auto_20191101_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_area_states',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
