# Generated by Django 2.2.5 on 2019-11-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20191101_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='properties_serviced',
        ),
    ]
