# Generated by Django 2.2.5 on 2019-11-01 01:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_remove_vendor_properties_serviced'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='properties_serviced',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
