# Generated by Django 2.2.5 on 2019-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_vendor_properties_serviced'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner_phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
