# Generated by Django 2.2.5 on 2019-11-02 17:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_community_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmingroup',
            name='pending_admins',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
