# Generated by Django 2.2.5 on 2019-11-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_communityadmingroup_pending_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.TagCollection'),
        ),
    ]
