# Generated by Django 2.2.5 on 2019-11-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_auto_20191104_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('rank',)},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='order',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='tagcollection',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('rank', 'name', 'tag_collection')},
        ),
    ]
