# Generated by Django 2.2.5 on 2019-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20191108_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_and_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='onboarding_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
