# Generated by Django 2.2.5 on 2019-11-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20191108_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vendor_tags', to='database.Tag'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=10000)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.UserProfile')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ('title',),
            },
        ),
    ]
