# Generated by Django 2.2.5 on 2019-11-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_auto_20191112_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Action'),
        ),
    ]
