# Generated by Django 2.2.5 on 2019-11-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_remove_data_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('rank', '-start_date_and_time')},
        ),
    ]
