# Generated by Django 2.2.5 on 2019-11-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0063_auto_20191115_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Media'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
