# Generated by Django 2.2.5 on 2019-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_auto_20191117_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='starred',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
