# Generated by Django 2.2.5 on 2019-11-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20191118_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='reported_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
