# Generated by Django 2.2.5 on 2019-11-25 04:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('path',)},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='path',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_body',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='trace',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestateunit',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Community'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Community'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile'),
        ),
    ]
