# Generated by Django 2.2.5 on 2019-12-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_action_calculator_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateunit',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Community'),
        ),
    ]
