# Generated by Django 2.2.8 on 2019-12-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_auto_20191202_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(default='', max_length=100)),
                ('deploy_commander', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deployments',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='featured_summary',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile')),
            ],
            options={
                'db_table': 'team_members_and_admins',
                'unique_together': {('team', 'user')},
            },
        ),
    ]
