# Generated by Django 2.2.8 on 2019-12-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_auto_20191207_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
