# Generated by Django 2.2.8 on 2019-12-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_auto_20191208_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile')),
            ],
            options={
                'db_table': 'community_members_and_admins',
                'unique_together': {('community', 'user')},
            },
        ),
    ]
