# Generated by Django 2.2.8 on 2019-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subdomain',
            unique_together=set(),
        ),
    ]
