# Generated by Django 2.2.8 on 2019-12-10 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_auto_20191208_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_team_admin_message',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Team'),
        ),
    ]
