# Generated by Django 2.2.8 on 2019-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0078_auto_20191210_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepagesettings',
            name='donation_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
