# Generated by Django 2.2.8 on 2020-01-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_donatepagesettings_donation_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'ordering': ('-version',)},
        ),
        migrations.AlterField(
            model_name='data',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Tag'),
        ),
    ]
