# Generated by Django 2.2.9 on 2020-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0080_auto_20200109_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_and_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_and_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
