# Generated by Django 2.2.9 on 2020-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0082_auto_20200311_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='other_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
