# Generated by Django 3.0.7 on 2020-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0085_auto_20200730_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='video',
        ),
        migrations.AddField(
            model_name='team',
            name='video_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
