# Generated by Django 3.0.7 on 2020-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0085_auto_20200807_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
