# Generated by Django 3.1.6 on 2021-03-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0086_auto_20201116_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='geography_type',
            field=models.CharField(blank=True, choices=[('ZIPCODE', 'Community defined by one or more zipcodes'), ('CITY', 'Community defined by one or more cities or towns'), ('COUNTY', 'Community defined by one or more counties'), ('STATE', 'Community defined by one or more states'), ('COUNTRY', 'Community defined by a country'), ('NON_GEOGRAPHIC', 'A non-geographic community')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='location_set',
            field=models.ManyToManyField(blank=True, to='database.Location'),
        ),
        migrations.AddField(
            model_name='realestateunit',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('STATE_ONLY', 'State Only'), ('ZIP_CODE_ONLY', 'Zip Code Only'), ('CITY_ONLY', 'City Only'), ('COUNTY_ONLY', 'County Only'), ('COUNTRY_ONLY', 'Country Only'), ('FULL_ADDRESS', 'FULL ADDRESS')], max_length=15),
        ),
    ]
