# Generated by Django 3.0.7 on 2021-02-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0086_auto_20201116_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='zipcodes',
            field=models.ManyToManyField(blank=True, to='database.Location'),
        ),
        migrations.AddField(
            model_name='realestateunit',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Location'),
        ),
    ]
