# Generated by Django 3.0.7 on 2021-02-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0087_auto_20210201_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='zipcodes',
            new_name='location_set',
        ),
        migrations.AddField(
            model_name='community',
            name='geography_type',
            field=models.CharField(blank=True, choices=[('ZIPCODE', 'Community defined by one or more zipcodes'), ('CITY', 'Community defined by one or more cities or towns'), ('COUNTY', 'Community defined by one or more counties'), ('STATE', 'Community defined by one or more states'), ('COUNTRY', 'Community defined by a country'), ('NON_GEOGRAPHIC', 'A non-geographic community')], max_length=15, null=True),
        ),
    ]
