# Generated by Django 3.1.6 on 2021-04-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0088_auto_20210330_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=100),
        ),
    ]
