# Generated by Django 3.1.6 on 2021-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0088_auto_20210214_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('STATE_ONLY', 'State Only'), ('ZIP_CODE_ONLY', 'Zip Code Only'), ('CITY_ONLY', 'City Only'), ('COUNTY_ONLY', 'County Only'), ('COUNTRY_ONLY', 'Country Only'), ('FULL_ADDRESS', 'FULL ADDRESS')], max_length=15),
        ),
    ]
