# Generated by Django 3.1.6 on 2021-04-06 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
#        ('database', '0087_auto_20210126_1334'),
        ('database', '0089_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='favicon_image',
        ),
        migrations.AddField(
            model_name='community',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_favicon', to='database.media'),
        ),
        migrations.CreateModel(
            name='TestimonialsPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.CharField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'TestimonialsPageSettings',
                'db_table': 'testimonials_page_settings',
            },
        ),
        migrations.CreateModel(
            name='EventsPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.CharField(blank=True, max_length=100)),
                ('more_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'EventsPageSettings',
                'db_table': 'events_page_settings',
            },
        ),
    ]
