# Generated by Django 3.1.6 on 2021-02-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0087_auto_20210126_1334'),
        ('database', '0089_auto_20210215_1901'),
    ]

    operations = [
    ]
