# Generated by Django 3.0.12 on 2021-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20210406_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
