# Generated by Django 3.0.14 on 2021-06-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20210406_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEquivalency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.BigIntegerField()),
                ('explanation', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Media')),
            ],
        ),
    ]
