# Generated by Django 3.0.14 on 2021-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20210406_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color',
            field=models.TextField(default='#000000', max_length=7, null=True),
        ),
    ]
