# Generated by Django 3.0.12 on 2021-07-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0091_auto_20210609_1814'),
        ('database', '0091_auto_20210702_1352'),
    ]

    operations = [
    ]
