# Generated by Django 3.1.6 on 2021-02-28 01:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0091_auto_20210228_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipprofile',
            name='client',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
