# Generated by Django 3.0.12 on 2021-07-10 03:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0092_merge_20210710_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepagesettings',
            name='featured_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
