# Generated by Django 3.0.14 on 2021-07-07 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0092_event_is_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recurring_type', models.CharField(max_length=1, null=True)),
                ('separation_count', models.PositiveIntegerField(null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('month_of_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Event')),
            ],
        ),
    ]
