# Generated by Django 3.1.12 on 2021-08-12 22:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0093_auto_20210710_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='RecurringEventException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('former_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_event', to='database.event')),
                ('rescheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.event')),
            ],
        ),
    ]
