# Generated by Django 3.0.14 on 2021-07-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0093_recurringpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_cancelled', models.BooleanField(default=True)),
                ('is_rescheduled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_event', to='database.Event')),
                ('rescheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Event')),
            ],
        ),
    ]
