# Generated by Django 3.0.14 on 2021-06-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0093_auto_20210625_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeduser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
