# Generated by Django 3.0.14 on 2021-06-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0094_auto_20210625_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedUser',
        ),
    ]
