# Generated by Django 3.0.14 on 2021-07-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0094_cancelledevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancelledEvent',
            new_name='RecurringEventException',
        ),
    ]
