# Generated by Django 3.1.12 on 2021-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_auto_20210813_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='attained_carbon_footprint_reduction',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='attained_number_of_actions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='attained_number_of_households',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='organic_attained_carbon_footprint_reduction',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='organic_attained_number_of_actions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='organic_attained_number_of_households',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
