# Generated by Django 3.1.12 on 2021-08-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_auto_20210812_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringeventexception',
            name='former_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
