# Generated by Django 3.0.14 on 2021-07-07 20:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_auto_20210707_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring_pattern',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
