# Generated by Django 3.1.12 on 2021-08-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0096_auto_20210813_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='team_communities', to='database.Community'),
        ),
        migrations.AlterField(
            model_name='team',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_community', to='database.community'),
        ),
    ]
