# Generated by Django 3.1.12 on 2021-08-17 10:29

from django.db import models, migrations

def fill_communities(apps, schema_editor):
    """
        Adds the Community object in Team.community to the
        many-to-many relationship in Team.communities
    """
    Team = apps.get_model('database', 'Team')

    for team in Team.objects.all():
        team.communities.add(team.community)

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_auto_20210817_1028'),
    ]

    operations = [
        migrations.RunPython(fill_communities),
    ]
