# Generated by Django 3.0.14 on 2021-07-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_pastevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recurring_pattern',
            new_name='recurring_details',
        ),
    ]
