# Generated by Django 3.0.14 on 2021-07-08 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_auto_20210707_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='max_occurrences',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
