# Generated by Django 3.1.12 on 2021-08-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_auto_20210817_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='community',
            new_name='primary_community',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('primary_community', 'name')},
        ),
    ]
