# Generated by Django 3.1.12 on 2021-08-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0099_auto_20210817_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='community_teams', to='database.Community'),
        ),
        migrations.AlterField(
            model_name='team',
            name='primary_community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_community_teams', to='database.community'),
        ),
    ]
