# Generated by Django 3.0.14 on 2021-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0099_auto_20210708_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpattern',
            name='month_of_year',
        ),
    ]
