# Generated by Django 3.0.14 on 2021-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0100_remove_recurringpattern_month_of_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringeventexception',
            name='is_rescheduled',
        ),
        migrations.AddField(
            model_name='recurringeventexception',
            name='former_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringeventexception',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
