# Generated by Django 3.1.12 on 2021-08-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0100_auto_20210819_1745'),
        ('database', '0098_auto_20210815_1834'),
    ]

    operations = [
    ]
