# Generated by Django 3.0.14 on 2021-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0101_auto_20210712_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringeventexception',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
