# Generated by Django 3.1.12 on 2021-08-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0101_eventattendee_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendee',
            old_name='attendee',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('user', 'event')},
        ),
    ]
