# Generated by Django 3.0.14 on 2021-07-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0102_recurringeventexception_is_rescheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringeventexception',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='recurringeventexception',
            name='is_rescheduled',
        ),
    ]
