# Generated by Django 3.1.12 on 2021-08-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0102_auto_20210819_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='geographic_area',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='request_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='trace',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingstatement',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityadmingroup',
            name='pending_admins',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactuspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donatepagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactpagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestateunit',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_page_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key_contact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='properties_serviced',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_area_states',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='verification_checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorspagesettings',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarbonEquivalency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.BigIntegerField()),
                ('explanation', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.media')),
            ],
        ),
    ]
