# Generated by Django 3.1.12 on 2021-08-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0102_auto_20210819_2202'),
        ('database', '0101_merge_20210819_2254'),
    ]

    operations = [
    ]
