# Generated by Django 3.0.14 on 2021-07-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0103_auto_20210713_1022'),
        ('database', '0093_auto_20210710_0325'),
    ]

    operations = [
    ]
