# Generated by Django 3.1.12 on 2021-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0104_auto_20210826_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonequivalency',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carbonequivalency',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='community_vendors', to='database.Community'),
        ),
    ]
