# Generated by Django 3.1.12 on 2021-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0105_auto_20210829_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonequivalency',
            name='value',
            field=models.FloatField(),
        ),
    ]
