# Generated by Django 3.1.12 on 2021-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0105_auto_20210901_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonequivalency',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
