# Generated by Django 3.1.12 on 2021-09-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0106_carbonequivalency_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCommunityWebsiteDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_website', to='database.community')),
            ],
            options={
                'db_table': 'custom_community_website_domain',
            },
        ),
    ]
