# Generated by Django 3.1.13 on 2021-10-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0108_auto_20211007_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='deviceprofile',
            name='user_profiles',
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, null=True, to='database.UserProfile'),
        ),
    ]
