# Generated by Django 3.1.13 on 2021-11-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0109_deviceprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
