# Generated by Django 3.1.13 on 2021-11-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0109_auto_20211119_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.CharField(blank=True, max_length=100)),
                ('more_info', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'SigninPageSettings',
                'db_table': 'signin_page_settings',
            },
        ),
        migrations.CreateModel(
            name='RegisterPageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('sub_title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('featured_video_link', models.CharField(blank=True, max_length=100)),
                ('more_info', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(blank=True, default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
            ],
            options={
                'verbose_name_plural': 'RegisterPageSettings',
                'db_table': 'register_page_settings',
            },
        ),
    ]
