# Generated by Django 3.1.13 on 2021-12-08 20:05

import array
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0110_registerpagesettings_signinpagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='visit_log',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visit_log',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
