# Generated by Django 3.1.13 on 2021-12-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0111_auto_20211208_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='database.media'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='database.media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='images',
            field=models.ManyToManyField(related_name='teams', to='database.Media'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='database.media'),
        ),
        migrations.CreateModel(
            name='UserMediaUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_universal', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communities', models.ManyToManyField(related_name='community_uploads', to='database.Community')),
                ('media', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to='database.media')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploads', to='database.userprofile')),
            ],
        ),
    ]
