# Generated by Django 3.1.14 on 2022-02-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0113_auto_20220216_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, to='database.Community'),
        ),
    ]
