# Generated by Django 3.1.14 on 2022-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0115_auto_20220223_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_email',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_message',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
