# Generated by Django 3.1.14 on 2022-08-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_message_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('scope', models.CharField(default='USER_FRONTEND', max_length=100)),
                ('audience', models.CharField(default='EVERYONE', max_length=100)),
                ('user_audience', models.CharField(default='EVERYONE', max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('communities', models.ManyToManyField(blank=True, related_name='community_feature_flags', to='database.Community')),
                ('users', models.ManyToManyField(blank=True, related_name='user_feature_flags', to='database.UserProfile')),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='image_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.imagesequence'),
        ),
    ]
