# Generated by Django 3.1.14 on 2022-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_message_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('on_for_everyone', models.BooleanField(default=False)),
                ('is_frontend', models.BooleanField(default=False)),
                ('is_backend', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('communities', models.ManyToManyField(related_name='community_feature_flags', to='database.Community')),
                ('users', models.ManyToManyField(related_name='user_feature_flags', to='database.UserProfile')),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ('-name',),
            },
        ),
    ]
