# Generated by Django 3.1.14 on 2022-08-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediaupload',
            name='is_action_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermediaupload',
            name='is_community_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermediaupload',
            name='is_event_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermediaupload',
            name='is_testimonial_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermediaupload',
            name='is_vendor_image',
            field=models.BooleanField(default=False),
        ),
    ]
