# Generated by Django 3.2.4 on 2022-09-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0119_approve_actions_events_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('portal', models.CharField(default='ADMIN_FRONTEND_PORTAL', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=10000)),
                ('by_super_admin', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actions', models.ManyToManyField(blank=True, to='database.Action')),
                ('actor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='footages', to='database.userprofile')),
                ('communities', models.ManyToManyField(blank=True, to='database.Community')),
                ('events', models.ManyToManyField(blank=True, to='database.Event')),
                ('images', models.ManyToManyField(blank=True, to='database.Media')),
                ('messages', models.ManyToManyField(blank=True, to='database.Message')),
                ('related_users', models.ManyToManyField(blank=True, related_name='appearances', to='database.UserProfile')),
                ('teams', models.ManyToManyField(blank=True, to='database.Team')),
                ('testimonials', models.ManyToManyField(blank=True, to='database.Testimonial')),
                ('vendors', models.ManyToManyField(blank=True, to='database.Vendor')),
            ],
            options={
                'db_table': 'footages',
                'ordering': ('-id',),
            },
        ),
    ]
