# Generated by Django 3.2.4 on 2022-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0120_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media_tags', to='database.Tag'),
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('order', '-id')},
        ),
        #migrations.AddField(
        #    model_name='usermediaupload',
        #    name='info',
        #    field=models.JSONField(blank=True, null=True),
        #),
    ]
