# Generated by Django 3.1.14 on 2022-11-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0122_auto_20221012_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='communities_under_publicity',
            field=models.ManyToManyField(blank=True, related_name='event_access_selections', to='database.Community'),
        ),
        migrations.AddField(
            model_name='event',
            name='publicity',
            field=models.CharField(default='OPEN', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='shared_to',
            field=models.ManyToManyField(blank=True, related_name='events_from_others', to='database.Community'),
        ),
    ]
