# Generated by Django 3.1.14 on 2022-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0123_auto_20221017_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
