# Generated by Django 3.1.14 on 2022-12-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0123_auto_20221108_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_dates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
