# Generated by Django 3.1.14 on 2022-11-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0124_auto_20221022_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='live_at',
        ),
    ]
