# Generated by Django 3.2.4 on 2023-03-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0126_auto_20221229_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-id', 'rank', 'title']},
        ),
        migrations.AlterModelOptions(
            name='useractionrel',
            options={'ordering': ('-id', 'status', 'user', 'action')},
        ),
        migrations.CreateModel(
            name='PolicyAcceptanceRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='MOU', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_policies', to='database.userprofile')),
            ],
        ),
    ]
