# Generated by Django 3.1.14 on 2023-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0127_auto_20230306_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude_from_nudge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
