# Generated by Django 3.2.4 on 2023-03-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0127_auto_20230306_0944'),
        ('database', '0128_policyacceptancerecords_policy'),
    ]

    operations = [
    ]
