# Generated by Django 3.1.14 on 2023-04-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0128_auto_20230412_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='CommunitySnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('is_live', models.BooleanField(blank=True, default=False)),
                ('households_total', models.CharField(blank=True, max_length=100)),
                ('households_user_reported', models.CharField(blank=True, max_length=100)),
                ('households_manual_addition', models.CharField(blank=True, max_length=100)),
                ('households_partner', models.CharField(blank=True, max_length=100)),
                ('user_count', models.CharField(blank=True, max_length=100)),
                ('actions_live_count', models.CharField(blank=True, max_length=100)),
                ('actions_total', models.CharField(blank=True, max_length=100)),
                ('actions_partner', models.CharField(blank=True, max_length=100)),
                ('actions_user_reported', models.CharField(blank=True, max_length=100)),
                ('carbon_total', models.CharField(blank=True, max_length=100)),
                ('carbon_user_reported', models.CharField(blank=True, max_length=100)),
                ('carbon_manual_addition', models.CharField(blank=True, max_length=100)),
                ('carbon_partner', models.CharField(blank=True, max_length=100)),
                ('guest_count', models.CharField(blank=True, max_length=100)),
                ('actions_manual_addition', models.CharField(blank=True, max_length=100)),
                ('events_hosted_current', models.CharField(blank=True, max_length=100)),
                ('events_hosted_past', models.CharField(blank=True, max_length=100)),
                ('my_events_shared_current', models.CharField(blank=True, max_length=100)),
                ('my_events_shared_past', models.CharField(blank=True, max_length=100)),
                ('events_borrowed_from_others_current', models.CharField(blank=True, max_length=100)),
                ('events_borrowed_from_others_past', models.CharField(blank=True, max_length=100)),
                ('teams_count', models.CharField(blank=True, max_length=100)),
                ('subteams_count', models.CharField(blank=True, max_length=100)),
                ('testimonials_count', models.CharField(blank=True, max_length=100)),
                ('service_providers_count', models.CharField(blank=True, max_length=100)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.community')),
            ],
            options={
                'db_table': 'community_snapshots',
            },
        ),
    ]
