# Generated by Django 3.1.14 on 2023-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0128_communitytimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytimestamp',
            name='actions_live_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='actions_partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='actions_total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='actions_user_reported',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='carbon_manual_addition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='carbon_partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='carbon_total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='carbon_user_reported',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='events_hosted',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='households_manual_addition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='households_partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='households_total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='households_user_reported',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='not_live_actions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='not_live_events',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='user_count',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
