# Generated by Django 3.1.14 on 2023-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0129_auto_20230405_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytimestamp',
            name='events_hosted',
        ),
        migrations.RemoveField(
            model_name='communitytimestamp',
            name='not_live_actions',
        ),
        migrations.RemoveField(
            model_name='communitytimestamp',
            name='not_live_events',
        ),
        migrations.RemoveField(
            model_name='communitytimestamp',
            name='placeholder_events_at_large',
        ),
        migrations.RemoveField(
            model_name='communitytimestamp',
            name='placeholder_events_shared',
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='actions_manual_addition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='events_borrowed_from_others_current',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='events_borrowed_from_others_past',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='events_hosted_current',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='events_hosted_past',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='guest_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='my_events_shared_current',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='my_events_shared_past',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='service_providers_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='subteams_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='teams_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitytimestamp',
            name='testimonials_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitytimestamp',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
