# Generated by Django 3.1.14 on 2023-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0130_auto_20230406_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
