# Generated by Django 3.1.14 on 2023-05-01 16:25

from django.db import migrations, models

def fill_empty_strings(apps, schema_editor):
    Snapshots = apps.get_model('database', 'CommunitySnapshot')

    for snap in Snapshots.objects.all():
        for f in snap._meta.get_fields():
                if getattr(snap, f.attname)== "":  
                    setattr(snap, f.attname, 0)
                    snap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0131_auto_20230428_1059'),
    ]

    operations = [
        migrations.RunPython(fill_empty_strings),
    ]
