# Generated by Django 3.1.14 on 2023-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0132_auto_20230501_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysnapshot',
            name='actions_live_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='actions_manual_addition',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='actions_partner',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='actions_total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='actions_user_reported',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='carbon_manual_addition',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='carbon_partner',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='carbon_total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='carbon_user_reported',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='events_borrowed_from_others_current',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='events_borrowed_from_others_past',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='events_hosted_current',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='events_hosted_past',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='households_manual_addition',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='households_partner',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='households_total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='households_user_reported',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='member_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='my_events_shared_current',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='my_events_shared_past',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='primary_community_users_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='service_providers_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='subteams_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='teams_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communitysnapshot',
            name='testimonials_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
