# Generated by Django 3.1.14 on 2023-05-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0010_auto_20230515_1714'),
        ('database', '0133_auto_20230501_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_category', to='carbon_calculator.category'),
        ),
        migrations.AddField(
            model_name='action',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_subcategory', to='carbon_calculator.subcategory'),
        ),
    ]
