# Generated by Django 3.1.14 on 2023-07-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0134_auto_20230515_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='has_accepted_cookies',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
