# Generated by Django 3.1.14 on 2023-07-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0134_auto_20230515_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_user_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_user_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_user_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_user_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
