# Generated by Django 3.1.14 on 2023-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0135_deviceprofile_has_accepted_cookies'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
