# Generated by Django 3.1.14 on 2023-09-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0136_auto_20230720_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureflag',
            name='owner',
        ),
    ]
