# Generated by Django 3.1.14 on 2023-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0136_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
