# Generated by Django 3.1.14 on 2023-09-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0136_auto_20230720_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hash',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
