# Generated by Django 3.1.14 on 2023-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_remove_featureflag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='postmark_contact_info',
            field=models.JSONField(blank=True, default={'alias': None, 'is_validated': False, 'sender_id': None}, null=True),
        ),
    ]
