# Generated by Django 3.1.14 on 2023-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_remove_featureflag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='contact_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='contact_sender_alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
