# Generated by Django 3.1.14 on 2023-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_postmarktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmarktemplate',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
