# Generated by Django 3.1.14 on 2023-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_media_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='hash',
            field=models.TextField(blank=True, db_index=True, max_length=10000),
        ),
    ]
