# Generated by Django 3.1.14 on 2023-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_auto_20230718_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
