# Generated by Django 3.1.14 on 2023-07-27 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0138_postmarktemplate_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmarktemplate',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
