# Generated by Django 3.1.14 on 2023-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0138_auto_20230916_1912'),
        ('database', '0138_auto_20230920_1140'),
    ]

    operations = [
    ]
