# Generated by Django 3.1.14 on 2023-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0138_community_postmark_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='postmark_contact_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
