# Generated by Django 3.1.14 on 2023-10-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0139_merge_20230921_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scheduled_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
