# Generated by Django 3.1.14 on 2023-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0139_auto_20230914_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='sender_signature_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
