# Generated by Django 3.2 on 2023-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0140_usermediaupload_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='schedule_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermediaupload',
            name='publicity',
            field=models.CharField(blank=True, default='OPEN_TO', max_length=100, null=True),
        ),
    ]
