# Generated by Django 3.1.14 on 2023-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0140_usermediaupload_publicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediaupload',
            name='publicity',
            field=models.CharField(blank=True, default='OPEN_TO', max_length=100, null=True),
        ),
    ]
