# Generated by Django 3.1.14 on 2023-10-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0138_auto_20230919_0704'),
        ('database', '0140_usermediaupload_publicity'),
    ]

    operations = [
    ]
