# Generated by Django 3.2.22 on 2024-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
