# Generated by Django 3.2.22 on 2024-02-21 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_alter_event_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventNudgeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('more_info', models.JSONField(blank=True, null=True)),
                ('communities', models.ManyToManyField(blank=True, related_name='nudge_settings_communities', to='database.Community')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nudge_settings_creator', to='database.userprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_settings', to='database.event')),
            ],
        ),
    ]
