# Generated by Django 3.2.22 on 2024-02-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0145_auto_20240226_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnudgesetting',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='eventnudgesetting',
            name='settings',
        ),
        migrations.AddField(
            model_name='eventnudgesetting',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nudge_settings_last_updated_by', to='database.userprofile'),
        ),
        migrations.AddField(
            model_name='eventnudgesetting',
            name='never',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='eventnudgesetting',
            name='when_first_posted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='eventnudgesetting',
            name='within_1_week',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='eventnudgesetting',
            name='within_30_days',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
