# Generated by Django 3.2.22 on 2024-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0146_auto_20240227_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='allow_opt_in',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
