# Generated by Django 4.2.1 on 2024-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0148_auto_20240331_2135'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communitynotificationsetting',
            index=models.Index(fields=['community', 'notification_type'], name='database_co_communi_8cd80f_idx'),
        ),
    ]
