# Generated by Django 4.2.1 on 2024-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_custommenu_custommenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommenuitem',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
