# Generated by Django 4.2.1 on 2024-06-19 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_communitynotificationsetting_database_co_communi_8cd80f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('is_footer_menu', models.BooleanField(blank=True, default=False)),
                ('more_info', models.JSONField(blank=True, null=True)),
                ('community_logo_link', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_menus', to='database.community')),
            ],
            options={
                'verbose_name_plural': 'CustomMenus',
                'db_table': 'custom_menus',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CustomMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_link_external', models.BooleanField(blank=True, default=False)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='database.custommenu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='database.custommenuitem')),
            ],
            options={
                'verbose_name_plural': 'CustomMenuItems',
                'db_table': 'custom_menu_items',
                'ordering': ('order',),
            },
        ),
    ]
