# Generated by Django 4.2.1 on 2024-06-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_communitynotificationsetting_database_co_communi_8cd80f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
        migrations.AddField(
            model_name='menu',
            name='community_logo_link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
