# Generated by Django 4.2.1 on 2024-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0150_alter_custommenuitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommenuitem',
            name='is_link_external',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='custommenuitem',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
