# Generated by Django 4.2.1 on 2024-06-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0150_menu_community_menu_community_logo_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_default',
            new_name='is_custom',
        ),
    ]
