# Generated by Django 4.2.1 on 2024-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0153_staticsitetext_supportedlanguage_texthash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationscache',
            name='id',
        ),
        migrations.AlterField(
            model_name='translationscache',
            name='hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='TextHash',
        ),
    ]
