# Generated by Django 4.2.1 on 2024-08-12 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0012_campaign_about_us_title'),
        ('database', '0153_supportedlanguage_translationscache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSupportedLanguage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_languages', to='apps__campaigns.campaign')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.supportedlanguage')),
            ],
            options={
                'db_table': 'campaign_supported_languages',
            },
        ),
    ]
