# Generated by Django 4.2.1 on 2024-08-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0154_remove_translationscache_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticSiteText',
        ),
    ]
