# Generated by Django 4.2.1 on 2024-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0155_testimonial_audience_testimonial_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='sharing_type',
            field=models.CharField(blank=True, choices=[('Public', 'OPEN'), ('Private', 'CLOSED'), ('Open to', 'OPEN_TO'), ('Closed to', 'CLOSED_TO')], default='OPEN', max_length=100, null=True),
        ),
    ]
