# Generated by Django 4.2.1 on 2024-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0155_testimonial_approved_for_sharing_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialautosharesettings',
            name='share_from_location_type',
            field=models.CharField(choices=[('STATE', 'State'), ('CITY', 'City'), ('ZIPCODE', 'Zipcode'), ('COUNTY', 'County'), ('COUNTRY', 'Country'), ('FULL_ADDRESS', 'Full Address')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialautosharesettings',
            name='share_from_location_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
