# Generated by Django 4.2.1 on 2024-10-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0018_campaignmedia_order'),
        ('database', '0156_alter_testimonial_sharing_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignsupportedlanguage',
            unique_together={('language', 'campaign')},
        ),
    ]
