# Generated by Django 4.2.1 on 2024-09-05 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0156_alter_testimonialautosharesettings_share_from_location_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='approved_for_sharing_by',
        ),
        migrations.CreateModel(
            name='TestimonialSharedCommunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_shares', to='database.community')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_communities', to='database.testimonial')),
            ],
            options={
                'unique_together': {('community', 'testimonial')},
            },
        ),
    ]
