# Generated by Django 4.2.1 on 2024-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0157_remove_testimonial_approved_for_sharing_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
