# Generated by Django 4.2.1 on 2024-11-12 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0157_alter_campaignsupportedlanguage_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'custom_pages',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CustomPageVersion',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='database.custompage')),
            ],
            options={
                'db_table': 'custom_page_versions',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='custompage',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_version', to='database.custompageversion'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
        migrations.CreateModel(
            name='CommunityCustomPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sharing_type', models.CharField(choices=[('Public', 'OPEN'), ('Private', 'CLOSED'), ('Open to', 'OPEN_TO'), ('Closed to', 'CLOSED_TO')], default='OPEN', max_length=100)),
                ('audience', models.ManyToManyField(blank=True, related_name='custom_pages_audience', to='database.community')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pages', to='database.community')),
                ('custom_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.custompage')),
            ],
            options={
                'db_table': 'community_custom_pages',
                'unique_together': {('community', 'custom_page')},
            },
        ),
        migrations.CreateModel(
            name='CommunityCustomPageShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_custom_pages', to='database.community')),
                ('community_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='database.communitycustompage')),
            ],
            options={
                'db_table': 'community_custom_page_shares',
                'unique_together': {('community_page', 'community')},
            },
        ),
    ]
