# Generated by Django 4.2.1 on 2024-09-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0158_testimonial_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialautosharesettings',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_auto_share_settings', to='database.community'),
        ),
    ]
