# Generated by Django 4.2.1 on 2024-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0159_alter_testimonialautosharesettings_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialautosharesettings',
            name='share_from_location_type',
            field=models.CharField(blank=True, choices=[('STATE', 'State'), ('CITY', 'City'), ('ZIPCODE', 'Zipcode'), ('COUNTY', 'County'), ('COUNTRY', 'Country'), ('FULL_ADDRESS', 'Full Address')], max_length=100, null=True),
        ),
    ]
