# Generated by Django 4.2.1 on 2025-05-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0159_remove_action_primary_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialautosharesettings',
            name='excluded_tags',
        ),
    ]
