# Generated by Django 4.2.1 on 2024-09-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0160_alter_testimonialautosharesettings_share_from_location_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='shared_with',
            new_name='audience',
        ),
    ]
