# Generated by Django 3.1.14 on 2023-12-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyoverview',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_overview', to='apps__campaigns.technology'),
        ),
    ]
