# Generated by Django 3.2.22 on 2024-01-02 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_event', to='apps__campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.event')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_event', to='apps__campaigns.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CampaignTechnologyEvent',
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='technology_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.technologyevent'),
        ),
    ]
