# Generated by Django 3.2.22 on 2023-12-19 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlike',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaignlike',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologyview',
            name='email',
        ),
        migrations.AddField(
            model_name='campaignlike',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigntechnologyview',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
