# Generated by Django 3.2.22 on 2023-12-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTechnologyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignTechnologyFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('community_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='campaignlike',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaignlike',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologyview',
            name='email',
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaignlike',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigntechnologyview',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaigncommunity',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_community', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignmanager',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_manager', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignpartner',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_partner', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaigntechnology',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_campaign', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaigntechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology', to='apps__campaigns.technology'),
        ),
        migrations.AlterField(
            model_name='campaigntechnologytestimonial',
            name='campaign_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_testimonials', to='apps__campaigns.campaigntechnology'),
        ),
        migrations.AlterField(
            model_name='campaigntechnologytestimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_technology_testimonial_image', to='database.media'),
        ),
        migrations.AlterField(
            model_name='technologycoach',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_coach', to='apps__campaigns.technology'),
        ),
        migrations.AlterField(
            model_name='technologyvendor',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_vendor', to='apps__campaigns.technology'),
        ),
        migrations.DeleteModel(
            name='CampaignEvent',
        ),
        migrations.AddField(
            model_name='campaignview',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntechnologyfollow',
            name='campaign_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaigntechnology'),
        ),
        migrations.AddField(
            model_name='campaigntechnologyfollow',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
        migrations.AddField(
            model_name='campaigntechnologyfollow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
        migrations.AddField(
            model_name='campaigntechnologyevent',
            name='campaign_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_event', to='apps__campaigns.campaigntechnology'),
        ),
        migrations.AddField(
            model_name='campaigntechnologyevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.event'),
        ),
    ]
