# Generated by Django 3.1.14 on 2023-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmanager',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
