# Generated by Django 3.1.14 on 2023-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0002_auto_20231207_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='campaign_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaigntechnology'),
        ),
    ]
