# Generated by Django 3.1.14 on 2023-12-06 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0002_campaignmanager_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTechnologyTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaign')),
                ('campaign_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaigntechnology')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.testimonial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
