# Generated by Django 3.2.22 on 2023-12-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntechnologyevent',
            name='campaign_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_event', to='apps__campaigns.campaigntechnology'),
        ),
    ]
