# Generated by Django 3.2.22 on 2023-12-19 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0002_auto_20231219_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTechnologyFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('community_name', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaigntechnology')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
