# Generated by Django 3.2.22 on 2024-01-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0002_auto_20240102_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigntechnologytestimonial',
            old_name='anonymous',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='deal_section_image',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='body',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='community',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='title',
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_testimonial', to='database.testimonial'),
        ),
    ]
