# Generated by Django 3.2.22 on 2023-12-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0003_campaigntechnologyfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncommunity',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_community', to='database.community'),
        ),
        migrations.AlterField(
            model_name='campaigntechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology', to='apps__campaigns.technology'),
        ),
    ]
