# Generated by Django 3.2.22 on 2024-01-11 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0003_auto_20240105_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTechnologyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('campaign_technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_event', to='apps__campaigns.campaigntechnology')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='technologyevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='technologyevent',
            name='technology',
        ),
        migrations.DeleteModel(
            name='CampaignEvent',
        ),
        migrations.DeleteModel(
            name='TechnologyEvent',
        ),
    ]
