# Generated by Django 3.1.14 on 2023-12-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0004_auto_20231206_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntechnologytestimonial',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_technology_testimonials', to='database.media'),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
