# Generated by Django 3.2.22 on 2023-12-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0004_auto_20231219_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmanager',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_manager', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignpartner',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_partner', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='technologycoach',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_coach', to='apps__campaigns.technology'),
        ),
        migrations.AlterField(
            model_name='technologyvendor',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_vendor', to='apps__campaigns.technology'),
        ),
    ]
