# Generated by Django 3.1.14 on 2023-12-07 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0004_auto_20231207_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaign')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='technologyevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='technologyevent',
            name='technology',
        ),
        migrations.DeleteModel(
            name='CampaignTechnologyEvent',
        ),
        migrations.DeleteModel(
            name='TechnologyEvent',
        ),
    ]
