# Generated by Django 3.2.22 on 2023-12-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0005_auto_20231219_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntechnologytestimonial',
            name='campaign_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_testimonials', to='apps__campaigns.campaigntechnology'),
        ),
    ]
