# Generated by Django 3.1.14 on 2023-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0005_auto_20231206_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlink',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
