# Generated by Django 3.1.14 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0005_auto_20231207_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
