# Generated by Django 3.2.22 on 2024-01-13 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0005_auto_20240112_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='action_section',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='coaches_section',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='deal_section',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='more_info_section',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='overview_title',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='vendors_section',
        ),
        migrations.AddField(
            model_name='campaign',
            name='advert',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='coaches_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='deal_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='overview_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='vendors_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignaccountadmin',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technologydeal',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_deal', to='apps__campaigns.technology'),
        ),
    ]
