# Generated by Django 3.1.14 on 2023-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0006_auto_20231207_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignconfiguration',
            name='advert',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
