# Generated by Django 3.2.22 on 2024-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0006_auto_20240113_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmanager',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
