# Generated by Django 3.2.22 on 2023-12-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0006_alter_campaigntechnologytestimonial_campaign_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntechnologytestimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_technology_testimonial_image', to='database.media'),
        ),
    ]
