# Generated by Django 3.1.14 on 2023-12-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0007_campaignconfiguration_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='logo',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_image', to='database.media'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='primary_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_logo', to='database.media'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='secondary_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_logo', to='database.media'),
        ),
    ]
