# Generated by Django 3.2.22 on 2023-12-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0007_alter_campaigntechnologytestimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncommunity',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_community', to='apps__campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaigncommunity',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_event', to='apps__campaigns.campaign'),
        ),
    ]
