# Generated by Django 3.2.22 on 2024-01-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0007_campaignmanager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='more_info_section',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
