# Generated by Django 3.1.14 on 2023-12-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0008_auto_20231207_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfollow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campaignlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologylike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technologycoach',
            name='user',
        ),
        migrations.AddField(
            model_name='campaignfollow',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignfollow',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaignlike',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='technologycoach',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='technologycoach',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technologycoach',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.media'),
        ),
        migrations.AddField(
            model_name='technologycoach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
