# Generated by Django 3.2.22 on 2023-12-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0009_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntechnology',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_technology_campaign', to='apps__campaigns.campaign'),
        ),
    ]
