# Generated by Django 3.2.22 on 2024-01-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0142_auto_20231103_1404'),
        ('apps__campaigns', '0009_auto_20240120_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntechnologytestimonial',
            name='is_imported',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_technology', to='database.userprofile'),
        ),
    ]
