# Generated by Django 3.1.14 on 2023-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0009_auto_20231207_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
