# Generated by Django 3.2.22 on 2024-01-28 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_alter_event_external_link'),
        ('apps__campaigns', '0010_auto_20240121_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='coaches_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='newsletter_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='technologies_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigncommunity',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TechnologyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.media')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_action', to='apps__campaigns.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
