# Generated by Django 3.2.22 on 2024-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0011_auto_20240128_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='about_us_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
