# Generated by Django 3.1.14 on 2023-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0011_auto_20231208_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntechnology',
            name='coaches_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='deal_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='more_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='over_vew_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='vendors_section',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
