# Generated by Django 3.1.14 on 2023-12-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0012_auto_20231208_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='more_details',
        ),
        migrations.RemoveField(
            model_name='campaigntechnology',
            name='over_vew_section',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='deal_section',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='more_details',
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='action_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='deal_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.media'),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='more_info_section',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnology',
            name='overview_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
