# Generated by Django 4.2.1 on 2024-09-12 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0156_alter_testimonial_sharing_type'),
        ('apps__campaigns', '0012_campaign_about_us_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.media'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TechnologyFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_faq', to='apps__campaigns.technology')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('cta', models.JSONField(blank=True, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.media')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='callout_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callout_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='technology',
            name='faq_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_section', to='apps__campaigns.section'),
        ),
    ]
