# Generated by Django 3.1.14 on 2023-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0013_auto_20231208_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
