# Generated by Django 3.1.14 on 2023-12-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0014_campaigntechnologylike_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfollow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologylike',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologylike',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='campaignfollow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.userprofile'),
        ),
        migrations.AlterField(
            model_name='campaignfollow',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
    ]
