# Generated by Django 3.1.14 on 2023-12-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0143_event_technology'),
        ('apps__campaigns', '0015_auto_20231212_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntechnologylike',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
    ]
