# Generated by Django 3.2.22 on 2023-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0016_auto_20231212_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfollow',
            name='community_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
