# Generated by Django 4.2.1 on 2024-09-30 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0156_alter_testimonial_sharing_type'),
        ('apps__campaigns', '0016_campaign_banner_section_campaign_featured_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_media', to='apps__campaigns.campaign')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
