# Generated by Django 3.2.22 on 2023-12-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0017_campaignfollow_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaignaccount'),
        ),
    ]
