# Generated by Django 3.2.22 on 2023-12-15 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0018_alter_campaign_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignActivityTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('button_type', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
