# Generated by Django 4.2.1 on 2024-10-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0018_campaignmedia_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='call_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps__campaigns.calltoaction'),
        ),
    ]
