# Generated by Django 4.2.1 on 2024-10-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0019_technology_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='about_us_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='eligibility_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='get_in_touch_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_in_touch_section', to='apps__campaigns.section'),
        ),
        migrations.AddField(
            model_name='technology',
            name='new_deal_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_deals_section', to='apps__campaigns.section'),
        ),
    ]
