# Generated by Django 3.2.22 on 2023-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0019_auto_20231215_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='communities_section',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
