# Generated by Django 3.2.22 on 2023-12-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0020_campaign_communities_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntechnologylike',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaigntechnologyview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
