# Generated by Django 4.2.1 on 2024-10-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0157_alter_campaignsupportedlanguage_unique_together'),
        ('apps__campaigns', '0021_campaigncontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community'),
        ),
    ]
