# Generated by Django 3.2.22 on 2023-12-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0021_auto_20231215_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncommunity',
            name='help_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
