# Generated by Django 4.2.1 on 2025-03-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0023_campaign_manager_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='default_community_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_community_settings', to='apps__campaigns.calltoaction'),
        ),
    ]
