# Generated by Django 3.2.22 on 2023-12-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0023_campaigntechnologylike_community_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntechnologyview',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='campaigntechnologyview',
            name='user_agent',
        ),
    ]
