# Generated by Django 4.2.1 on 2025-03-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps__campaigns', '0024_campaign_default_community_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='apps__campaigns.campaign'),
        ),
    ]
