from _main_.settings import EMAIL_POSTMARK_TEMPLATE_DATA_DOWNLOAD, \
  EMAIL_POSTMARK_TEMPLATE_WEEKLY_REPORT, \
    EMAIL_POSTMARK_TEMPLATE_CADMIN_WEEKLY_REPORT

# API user types

STANDARD_USER = 'standard_user'
GUEST_USER = 'guest_user'
INVITED_USER = 'invited_user'    

# Postmark Template keys
DATA_DOWNLOAD_TEMPLATE_ID = EMAIL_POSTMARK_TEMPLATE_DATA_DOWNLOAD
SADMIN_EMAIL_TEMPLATE_ID = EMAIL_POSTMARK_TEMPLATE_WEEKLY_REPORT
CADMIN_EMAIL_TEMPLATE_ID = EMAIL_POSTMARK_TEMPLATE_CADMIN_WEEKLY_REPORT