USER_EVENTS_NUDGES_FF = "user-event-nudge-feature-flag"
COMMUNITY_ADMIN_WEEKLY_EVENTS_NUDGE_FF = "weekly-event-nudge-feature-flag"
#POSTMARK_COMMUNITY_EMAIL_SENDER_SIGNATURE_FF = "community-email-sender-signature-feature-flag"
#UPDATE_HTML_CONTENT_FORMAT_FF = "update-html-format-feature-flag"
REMOVE_DUPLICATE_IMAGE_FF = "remove-duplicate-images-feature-flag"
UPDATE_ACTIONS_CONTENT_FF = "update-actions-content-feature-flag"
REWIRING_AMERICA_MENU_ITEM_FF = "rewiring-america-menu-item-feature-flag"
