# Generated by Django 2.2.3 on 2019-08-30 10:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0025_auto_20190816_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('helptext', models.CharField(max_length=100, null=True)),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('average_points', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CCActionPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('action_status', models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE'), ('SAVE FOR LATER', 'SAVE_FOR_LATER')], db_index=True, default='TODO', max_length=100)),
                ('points', models.PositiveIntegerField(blank=True, default=0)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.CCAction')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.UserProfile')),
            ],
        ),
    ]
