# Generated by Django 2.2.5 on 2019-10-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '00001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcDefault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=40)),
                ('locality', models.CharField(max_length=40)),
                ('value', models.FloatField(default=0.0)),
                ('reference', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cc_defaults',
            },
        ),
        migrations.RemoveField(
            model_name='actionpoints',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='calcuser',
            name='town',
        ),
        migrations.AddField(
            model_name='actionpoints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.CalcUser'),
        ),
        migrations.AddField(
            model_name='calcuser',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
