# Generated by Django 2.2.3 on 2019-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccaction',
            name='helptext',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
