# Generated by Django 2.2.5 on 2019-11-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0002_auto_20191015_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calcuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calcuser',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
