# Generated by Django 2.2.5 on 2019-11-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0003_auto_20191114_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='carbon_calculator.CalcUser'),
        ),
    ]
