# Generated by Django 3.0.5 on 2020-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0003_event_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
