# Generated by Django 3.0.7 on 2020-11-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0086_auto_20201116_1419'),
        ('carbon_calculator', '0004_auto_20201116_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='database.UserProfile'),
        ),
    ]
