# Generated by Django 2.2.5 on 2019-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0004_auto_20190927_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='helptext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
