# Generated by Django 2.2.5 on 2019-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0004_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcuser',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calcuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calcuser',
            name='savings',
            field=models.IntegerField(default=0),
        ),
    ]
