# Generated by Django 3.0.5 on 2020-06-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0004_auto_20200429_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tltle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='maximum_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='minimum_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='typical_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carboncalculatormedia',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
