# Generated by Django 3.0.5 on 2020-06-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0005_auto_20200628_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='tltle',
            new_name='title',
        ),
    ]
