# Generated by Django 3.0.7 on 2020-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0005_auto_20201116_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncalculatormedia',
            name='name',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
