# Generated by Django 3.1.12 on 2021-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0006_carboncalculatormedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='questions',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionpoints',
            name='choices',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stationslist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skip_6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
