# Generated by Django 3.1.14 on 2023-08-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0007_auto_20210826_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host_org',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsor_org',
        ),
        migrations.RemoveField(
            model_name='group',
            name='member_list',
        ),
        migrations.RemoveField(
            model_name='org',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='station',
            name='icon',
        ),
        migrations.DeleteModel(
            name='ActionPoints',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
