# Generated by Django 2.2.5 on 2019-10-01 17:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20191001_1710'),
        ('carbon_calculator', '0008_auto_20190930_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=40)),
                ('choices', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('savings', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.UserProfile')),
            ],
            options={
                'db_table': 'cc_actionpoints',
            },
        ),
    ]
