# Generated by Django 3.1.14 on 2023-05-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0008_auto_20230502_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.category'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.subcategory'),
        ),
    ]
