# Generated by Django 3.0.7 on 2020-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0008_event_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='calcdefault',
            name='valid_date',
            field=models.DateField(null=True),
        ),
    ]
