# Generated by Django 2.2.5 on 2019-10-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0009_auto_20191010_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_action_picture', to='carbon_calculator.Media'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_host_logo', to='carbon_calculator.Media'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sponsor_logo', to='carbon_calculator.Media'),
        ),
    ]
