# Generated by Django 3.2 on 2023-11-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0010_auto_20231113_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.category'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.subcategory'),
        ),
    ]
