# Generated by Django 2.2.5 on 2019-10-11 17:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0010_auto_20191010_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('displayname', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('members', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'cc_group',
            },
        ),
        migrations.CreateModel(
            name='CalcUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('minimum_age', models.BooleanField(blank=True, default=False)),
                ('accepts_terms_and_conditions', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='carbon_calculator.Group')),
            ],
            options={
                'db_table': 'cc_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ActionPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=40)),
                ('choices', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('savings', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon_calculator.CalcUser')),
            ],
            options={
                'db_table': 'cc_actionpoints',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, to='carbon_calculator.Group'),
        ),
    ]
