# Generated by Django 2.2.5 on 2019-10-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0011_auto_20191011_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='CarbonCalculatorMedia',
        ),
        migrations.AddField(
            model_name='station',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_station_icon', to='carbon_calculator.CarbonCalculatorMedia'),
        ),
    ]
