# Generated by Django 4.2.1 on 2025-02-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0011_auto_20231113_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='old_category',
        ),
        migrations.RemoveField(
            model_name='action',
            name='picture',
        ),
    ]
