# Generated by Django 3.1.14 on 2022-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
