# Generated by Django 3.1.14 on 2022-03-14 22:35

from django.db import migrations, models
import django.db.models.deletion
import task_queue.type_constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('task_queue', '0002_task_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='operation',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_interval',
            new_name='recurring_interval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_queue_schedule', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=task_queue.type_constants.TaskStatus['active'], max_length=100, null=True),
        ),
    ]
