# Generated by Django 3.1.14 on 2022-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0002_auto_20220315_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_name',
            field=models.CharField(blank=True, choices=[('testing', 'testing'), ('send_email', 'send_email')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring_interval',
            field=models.CharField(blank=True, choices=[('EVERY_MINUTE', 'EVERY_MINUTE'), ('EVERY_HOUR', 'EVERY_HOUR'), ('EVERY_WEEK', 'EVERY_WEEK'), ('EVERY_DAY', 'EVERY_DAY'), ('EVERY_MONTH', 'EVERY_MONTH'), ('EVERY_QUARTER', 'EVERY_QUARTER'), ('EVERY_YEAR', 'EVERY_YEAR'), ('ONE_OFF', 'ONE_OFF')], max_length=100, null=True),
        ),
    ]
