# Generated by Django 3.1.14 on 2022-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0003_auto_20220316_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_name',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('Fibonacci', 'Fibonacci')], max_length=100, null=True),
        ),
    ]
