# Generated by Django 3.1.14 on 2023-01-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0005_task_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateField(blank=True, null=True),
        ),
    ]
