# Generated by Django 4.2.1 on 2024-08-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0006_task_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_automatic_task',
            field=models.BooleanField(default=False),
        ),
    ]
