# Generated by Django 4.2.1 on 2025-03-17 13:12

from django.db import migrations, models
import django.db.models.deletion
import task_queue.type_constants
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0007_task_is_automatic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default=task_queue.type_constants.TaskStatus['RUNNING'], max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='task_queue.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
