# Generated by Django 4.2.1 on 2025-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0008_taskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='RUNNING', max_length=100),
        ),
    ]
