# Generated by Django 3.0.14 on 2021-06-25 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_delete_importeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile')),
            ],
        ),
    ]
