# Generated by Django 3.0.14 on 2021-06-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0096_importeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importeduser',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='importeduser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
