# Generated by Django 3.0.14 on 2021-06-28 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_auto_20210628_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeduser',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
