# Generated by Django 3.0.14 on 2021-07-01 21:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_remove_userprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
