# Generated by Django 3.0.14 on 2021-07-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_auto_20210628_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedUser',
        ),
    ]
