# Generated by Django 3.0.14 on 2021-07-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_delete_importeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
