# Generated by Django 3.0.14 on 2021-06-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_importeduser_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importeduser',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
