# Generated by Django 3.0.14 on 2021-07-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0100_auto_20210628_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedUser',
        ),
    ]
